### ISSUE TITLE
name/create/destroy/reuse mrml nodes appropriately

### ISSUE THREAD

**Issue by ebrahimebrahim** [stephencrowell/SlicerEHRSandbox#9]
after loading the patient info from the server a bunch of times and querying a bunch of different observations, the data module shows table nodes all over the place:

![image](https://user-images.githubusercontent.com/1879759/201759043-32aa5287-5bc7-4038-856c-4ff3aa2817e5.png)

we should destroy or re-use table nodes appropriately (e.g. when patient info is re-loaded from the sever, we should not create a new PatientInfo_TableNode without destroying the old one)

We should name the observation table nodes more informatively, perhaps sometimes allowing ourselves to re-use existing observation table nodes rather than reloading data.

**Comment by stephencrowell** [comment]
I've fixed some of the additional table nodes being created, but there is still one case where we create additional table nodes.

When you select a patient and an observation, you will create the two table nodes (as expected); however, if you switch to a different layout/module and move back to SlicerEHRLayout, the tables will disappear and new table nodes will be created when selecting a patient/observation.

I originally thought the issue was coming from the the table view variables being reset (#14 was started because of this), but that didn't solve the problem. I am still looking into the issue, but if you have any ideas, I would be happy to hear them.

**Comment by stephencrowell** [comment]
Asked a question on [discourse](https://discourse.slicer.org/t/mrml-table-nodes-disconnecting-from-table-view-when-switching-layouts/26365) to see if this behavior is intended.
